#!/bin/sh

# Particularly useful in connection with tmux-jobs:
#
# for host in $hosts
# do
#     tmux-job "remembered_upgrade $host" upgrade-"$host"
# done

if test $# -ne 1
then
	echo >&2 "Usage: $0 <host>"
	exit 1
fi

ssh -oConnectTimeout=3 -t "$1" "apt-get update && apt-get upgrade"
retval=$?
[ "$retval" -eq 0 ] && date +%F_%T > ~/lastupgraded/"$1"
exit "$retval"
